# Generated by Django 3.2.4 on 2021-10-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='itemJson',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
